### ISSUE TITLE
博客404

### ISSUE THREAD

**Issue by bllli** [HelloGitHub-Team/HelloDjango-blog-tutorial#1]
https://www.zmrenwu.com/courses/django-blog-tutorial-v2/

![image](https://user-images.githubusercontent.com/19375623/61856983-d11bee80-aef5-11e9-9738-40bbcdba34db.png)

**Comment by zmrenwu** [comment]
Sorry，这个链接贴错了，请从下方的教程索引进去，下一个 commit 修复。
